export interface Ev { id:string; date:string; type:string; title:string; situation:string; what_people_believed:string; decision:string; what_happened:string; root_cause:string; recovery:string; lesson:string; trigger_conditions:string[]; }
const e = (id:string,date:string,type:string,title:string,situation:string,b:string,decision:string,h:string,rc:string,rec:string,lesson:string,tc:string[]):Ev =>
  ({id,date,type,title,situation,what_people_believed:b,decision,what_happened:h,root_cause:rc,recovery:rec,lesson,trigger_conditions:tc});

export const SEED: Ev[] = [
 e("E001","2025-02-08","FAILURE","Orders DB migration inside Saturday batch window","Orders DB schema migration scheduled Sat 02:00, during the 01:00-04:00 nightly batch window, because traffic looked low.","Low customer traffic meant low risk.","Run migration at Sat 02:00.","Batch jobs plus migration saturated disk IOPS; orders API timed out; migration rolled back at 03:40.","Batch window load (reconciliation jobs) was not counted as traffic; both compete for the same IOPS.","Rolled back, re-ran a week later outside the window.","Never run a migration inside the 01:00-04:00 batch window.",["database migration","Saturday overnight","batch window 01:00-04:00","shared IOPS"]),
 e("E002","2025-03-21","FAILURE","Friday deploy bundled with 3 dependency bumps","Friday deploy of Billing API bundled with three dependency upgrades to save release overhead.","Minor version bumps are safe; one release is cheaper than four.","Ship code and bumps together Friday afternoon.","New HTTP client default timeout changed; invoicing failed silently overnight; found Saturday morning.","Dependency change altered a default (timeout) nobody tested; bundled with code so blame was unclear.","Pinned old version, redeployed Saturday; reprocessed invoices.","Freeze dependency changes 48h before any Friday deploy; never bundle bumps with feature code.",["Friday deploy","dependency updates","bundled changes","default behavior change","weekend coverage"]),
 e("E003","2025-05-09","FAILURE","Friday deploy with Node major bump","Friday deploy of Tracking service including Node major version upgrade.","Same as E002 concerns were 'handled' by reading changelogs.","Deploy Friday with runtime bump.","Memory leak grew over the weekend; service OOM-killed Sunday; tracking lag for customers.","Node major changed GC/buffer behavior; leak only visible under weekend-long soak.","Rolled back Monday; upgraded later with soak test.","Dependency/runtime changes need a soak period and must not ship Friday (same pattern as E002).",["Friday deploy","dependency updates","runtime upgrade","weekend coverage","no soak test"]),
 e("E004","2025-06-15","FAILURE","Datastore migration with no load test","Moved Rates service from Postgres to a new managed store without a load test.","Vendor benchmarks showed it was faster.","Cut over on schedule.","p95 latency rose from 300ms to 2.4s under production load; quoting slowed.","Access pattern (many small reads) differed from vendor benchmark.","Reverted to Postgres within 6 hours.","Load-test with production-shaped traffic before any datastore migration.",["datastore migration","no load test","vendor benchmark trusted"]),
 e("E005","2025-07-11","FAILURE","Async queue introduced without ordering constraint","Shipment events moved to an async queue; ordering guarantee between status updates was not documented.","Queue is 'basically FIFO'.","Roll out queue to all shipments.","Out-of-order status updates showed delivered before dispatched; customers got wrong notifications.","Ordering was an operational constraint nobody wrote down.","Reverted to synchronous path.","Write an ADR documenting operational constraints (ordering, transactions, eviction) before architecture changes.",["architecture change","async queue","undocumented ordering constraint"]),
 e("E006","2025-08-22","FAILURE","Service split broke shared transaction","Split Payments and Invoicing into services; they previously shared a DB transaction.","Services are independent.","Split and deploy.","Partial writes: payments captured without invoices.","Implicit shared transaction was never documented.","Reverted split; added saga later.","Write an ADR documenting operational constraints before architecture changes.",["architecture change","service split","undocumented shared transaction"]),
 e("E007","2025-09-19","FAILURE","Cache layer added with wrong eviction policy","Added Redis cache in front of Rates; default eviction policy used.","Cache only speeds things up.","Enable cache in prod.","Eviction dropped hot keys unpredictably; stale rates served; latency spikes.","Required TTL/eviction semantics were never documented.","Disabled cache, re-added with explicit policy.","Write an ADR documenting operational constraints (eviction policy) before architecture changes.",["architecture change","caching","undocumented eviction policy"]),
 e("E008","2025-04-02","NOISE","Expired VPN certificate","VPN cert expired; engineers locked out for 30 minutes.","Renewal was automated.","Renew manually.","Access restored.","Calendar reminder missed.","Renewed.","Track cert expiry in calendar (not engineering-risk related).",["certificate expiry"]),
 e("E009","2025-08-05","NOISE","Routine Tuesday deploy","Ordinary Tuesday deploy of small UI copy change.","Trivial.","Deploy.","No issues.","n/a","n/a","Nothing notable.",["routine deploy"]),
 e("E010","2025-10-10","COUNTER-EXAMPLE","Friday deploy behind a feature flag","Friday deploy of Billing API change behind a feature flag with no dependency changes.","Flag allows instant off-switch.","Deploy Friday, flag off, enable Monday.","Went fine; flag enabled Monday with monitoring.","n/a","n/a","Friday deploys are acceptable when behind a flag with no dependency changes.",["Friday deploy","feature flag","no dependency changes"]),
 e("E011","2025-12-06","COUNTER-EXAMPLE","Saturday migration outside batch window after load test","Saturday 09:00 migration of Shipments DB, after load test, outside batch window.","Load-tested and off-window.","Proceed Saturday morning.","Went fine, no rollback.","n/a","n/a","Saturday migrations are fine outside the batch window and after a load test.",["database migration","Saturday","outside batch window","load tested"]),
 e("E012","2025-11-14","FAILURE","Friday deploy with config change and no rollback plan","Friday evening deploy of Notifications with new config and no tested rollback.","Config-only is low risk.","Deploy Friday 17:00.","Wrong config key disabled SMS alerts all weekend.","No rollback path or config validation.","Fixed Monday.","Every Friday deploy needs a tested rollback and config validation.",["Friday deploy","config change","no rollback plan","weekend coverage"]),
 e("E013","2025-01-18","FAILURE","Index rebuild during business hours","Rebuilt Customers index Tuesday 10:00.","Online rebuild is non-blocking.","Run in business hours.","Write locks stalled checkout for 12 minutes.","Online rebuild still takes brief locks under load.","Cancelled rebuild.","Run heavy DB maintenance off-peak and rehearse on a production-size copy.",["database maintenance","peak hours","no rehearsal"]),
 e("E014","2025-03-07","FAILURE","Thursday-night hotfix with no review","Hotfix pushed Thursday 23:00 to Pricing without peer review.","Small fix, urgent.","Push directly.","Rounding bug overcharged 40 invoices.","Skipped review; no test for the edge case.","Refunds issued.","Urgent hotfixes still need a second reviewer and a regression test.",["hotfix","no review","late night deploy"]),
 e("E015","2025-11-28","COUNTER-EXAMPLE","Tuesday deploy with staged rollout","Tuesday deploy of Tracking with dependency updates, 5% canary then full rollout.","Canary catches regressions.","Staged rollout over 24h.","Went fine; canary caught a minor issue early.","n/a","n/a","Dependency updates are safe midweek with a canary and time to observe.",["dependency updates","midweek deploy","canary rollout"]),
];
